name = "KroneckerArrays"
uuid = "05d0b138-81bc-4ff7-84be-08becefb1ccc"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.3.9"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
DiagonalArrays = "74fd4be6-21e2-4f6f-823a-4360d37c7a77"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FunctionImplementations = "7c7cc465-9c6a-495f-bdd1-f42428e86d0c"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MapBroadcast = "ebd9b9da-f48d-417c-9660-449667d60261"
MatrixAlgebraKit = "6c742aac-3347-4629-af66-fc926824e5e4"
TypeParameterAccessors = "7e5a90cf-f82e-492e-a09b-e3e26432c138"

[weakdeps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockSparseArrays = "2c9a651f-6452-4ace-a6ac-809f4280fbb4"
TensorAlgebra = "68bd88dc-f39d-4e12-b2ca-f046b68fcc6a"

[extensions]
KroneckerArraysBlockSparseArraysExt = ["BlockArrays", "BlockSparseArrays"]
KroneckerArraysTensorAlgebraExt = "TensorAlgebra"

[compat]
Adapt = "4.3"
BlockArrays = "1.6"
BlockSparseArrays = "0.9, 0.10.3"
DiagonalArrays = "0.3.19"
FillArrays = "1.13"
FunctionImplementations = "0.3.1, 0.4"
GPUArraysCore = "0.2"
LinearAlgebra = "1.10"
MapBroadcast = "0.1.10"
MatrixAlgebraKit = "0.6"
TensorAlgebra = "0.6.3, 0.7"
TypeParameterAccessors = "0.4.2"
julia = "1.10"

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]
